language: java

script: "./gradlew dist"

install:
  - echo sonatypeUsername=none >> gradle.properties
  - echo sonatypePassword=none >> gradle.properties

deploy:
  provider: releases
  api_key:
    secure: m+a8pXtE147nItyLKnnVJznyqoM14/IYMwDq+eS4+bHIctthqI91Q0cA7v0pz4DMNlq8ZRFT1wRjUGAA/qceMb15OMu+ZOoOoKTmrgozzoQgZt+AMHZ/O3SiMt9lJZCyRVh+OofeifBGOUdlTNTIveUPoqCr/g7jXq4lOMNBHGM=
  file: build/distributions/xmlcalabash1-sendmail-$TRAVIS_TAG.zip
  on:
    tags: true
    all_branches: true
